BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[CTHD] (
    [SOHD] INT NOT NULL,
    [MASP] CHAR(4) NOT NULL,
    [SL] INT,
    CONSTRAINT [pk_cthd] PRIMARY KEY CLUSTERED ([SOHD],[MASP])
);

-- CreateTable
CREATE TABLE [dbo].[HOADON] (
    [SOHD] INT NOT NULL,
    [NGHD] SMALLDATETIME,
    [MAKH] CHAR(4),
    [MANV] CHAR(4),
    [TRIGIA] MONEY,
    CONSTRAINT [pk_hd] PRIMARY KEY CLUSTERED ([SOHD])
);

-- CreateTable
CREATE TABLE [dbo].[KHACHHANG] (
    [MAKH] CHAR(4) NOT NULL,
    [HOTEN] VARCHAR(40),
    [DCHI] VARCHAR(50),
    [SODT] VARCHAR(20),
    [NGSINH] SMALLDATETIME,
    [NGDK] SMALLDATETIME,
    [DOANHSO] MONEY,
    CONSTRAINT [pk_kh] PRIMARY KEY CLUSTERED ([MAKH])
);

-- CreateTable
CREATE TABLE [dbo].[NHANVIEN] (
    [MANV] CHAR(4) NOT NULL,
    [HOTEN] VARCHAR(40),
    [SODT] VARCHAR(20),
    [NGVL] SMALLDATETIME,
    CONSTRAINT [pk_nv] PRIMARY KEY CLUSTERED ([MANV])
);

-- CreateTable
CREATE TABLE [dbo].[SANPHAM] (
    [MASP] CHAR(4) NOT NULL,
    [TENSP] VARCHAR(40),
    [DVT] VARCHAR(20),
    [NUOCSX] VARCHAR(40),
    [GIA] MONEY,
    CONSTRAINT [pk_sp] PRIMARY KEY CLUSTERED ([MASP])
);

-- AddForeignKey
ALTER TABLE [dbo].[CTHD] ADD CONSTRAINT [fk01_CTHD] FOREIGN KEY ([SOHD]) REFERENCES [dbo].[HOADON]([SOHD]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CTHD] ADD CONSTRAINT [fk02_CTHD] FOREIGN KEY ([MASP]) REFERENCES [dbo].[SANPHAM]([MASP]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[HOADON] ADD CONSTRAINT [fk01_HD] FOREIGN KEY ([MAKH]) REFERENCES [dbo].[KHACHHANG]([MAKH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[HOADON] ADD CONSTRAINT [fk02_HD] FOREIGN KEY ([MANV]) REFERENCES [dbo].[NHANVIEN]([MANV]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
